[build-system]
requires = ["setuptools==65.5.0", "wheel==0.40.0", "setuptools-scm==7.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "_version.py"
version_scheme = "no-guess-dev"